//! Build script:
//!  1. Put `memory.x` on the linker search path (0x26000 app offset).
//!  2. Turn the audio format into a build-time parameter so any feasible
//!     rate/channel/bit-depth is one env var away, and reject formats that
//!     can't fit a full-speed isochronous frame (>1023 bytes) at build time.
//!
//! Override per build:
//!   TESLAMIC_RATE=96000 TESLAMIC_CHANNELS=2 TESLAMIC_BITS=16 cargo build ...
//! Defaults: 48000 / 2 / 16 (so a plain `cargo build` is the original mic).
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    // ── Linker: memory.x ────────────────────────────────────────────────────
    fs::copy("memory.x", out.join("memory.x")).unwrap();
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=memory.x");
    println!("cargo:rerun-if-changed=build.rs");

    // ── Audio format parameters ─────────────────────────────────────────────
    let rate: u32 = envint("TESLAMIC_RATE", 48000);
    let channels: u32 = envint("TESLAMIC_CHANNELS", 2);
    let bits: u32 = envint("TESLAMIC_BITS", 16);
    // wChannelConfig (spatial positions). Defaults to the low `channels` bits;
    // override e.g. TESLAMIC_CHMASK=0x37 for 5.0 surround (L,R,C,LS,RS).
    let chmask: u32 = envint_maybe_hex("TESLAMIC_CHMASK", (1u32 << channels) - 1);
    // Test-tone frequency. The default 1000 Hz is a BAD diagnostic at 48 kHz:
    // it is exactly 48 samples, exactly one cycle per USB packet, so any fault
    // that merely reorders a packet's contents is inaudible. 997 Hz is the
    // classic audio-test frequency precisely because it shares no factor with
    // the frame rate, making such faults audible as roughness.
    let tone: u32 = envint("TESLAMIC_TONE_HZ", 1000);
    println!("cargo:rerun-if-env-changed=TESLAMIC_RATE");
    println!("cargo:rerun-if-env-changed=TESLAMIC_CHANNELS");
    println!("cargo:rerun-if-env-changed=TESLAMIC_BITS");
    println!("cargo:rerun-if-env-changed=TESLAMIC_CHMASK");
    println!("cargo:rerun-if-env-changed=TESLAMIC_TONE_HZ");

    assert!(matches!(bits, 16 | 24), "TESLAMIC_BITS must be 16 or 24 (got {bits})");
    assert!((1..=8).contains(&channels), "TESLAMIC_CHANNELS must be 1..=8 (got {channels})");
    assert!((8000..=192000).contains(&rate), "TESLAMIC_RATE out of range (got {rate})");
    assert!(chmask <= 0xFFFF, "TESLAMIC_CHMASK must fit 16 bits (got {chmask})");
    assert!(
        tone > 0 && tone < rate / 2,
        "TESLAMIC_TONE_HZ must be below Nyquist for {rate} Hz (got {tone})"
    );

    let bytes_per_sample = bits / 8;
    // Full-speed sends one packet per 1 ms frame; a fractional rate (e.g. 44100)
    // needs the ceiling number of samples in its biggest frame.
    let max_samples_per_frame = rate.div_ceil(1000);
    let max_bytes_per_frame = max_samples_per_frame * channels * bytes_per_sample;
    assert!(
        max_bytes_per_frame <= 1023,
        "format {rate} Hz / {channels}ch / {bits}-bit needs {max_bytes_per_frame} bytes/frame, \
         over the 1023-byte full-speed isochronous limit — not possible on this hardware"
    );

    let _ = max_samples_per_frame; // only needed for the feasibility check above
    let body = format!(
        "// Generated by build.rs from TESLAMIC_RATE/CHANNELS/BITS/CHMASK.\n\
         const SAMPLE_RATE: u32 = {rate};\n\
         const CHANNELS: usize = {channels};\n\
         const BITS: u8 = {bits};\n\
         const BYTES_PER_SAMPLE: usize = {bytes_per_sample};\n\
         const MAX_BYTES_PER_FRAME: usize = {max_bytes_per_frame};\n\
         const CHANNEL_MASK: u16 = {chmask};\n\
         const TONE_HZ: u32 = {tone};\n"
    );
    fs::write(out.join("format.rs"), body).unwrap();
}

fn envint(key: &str, default: u32) -> u32 {
    match env::var(key) {
        Ok(v) => v.trim().parse().unwrap_or_else(|_| panic!("{key} must be an integer (got {v:?})")),
        Err(_) => default,
    }
}

// Parse a decimal or 0x-prefixed hex integer.
fn envint_maybe_hex(key: &str, default: u32) -> u32 {
    match env::var(key) {
        Ok(v) => {
            let t = v.trim();
            let parsed = if let Some(hex) = t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")) {
                u32::from_str_radix(hex, 16)
            } else {
                t.parse()
            };
            parsed.unwrap_or_else(|_| panic!("{key} must be an integer (got {v:?})"))
        }
        Err(_) => default,
    }
}
